baseURL = "https://hydrosenselab.github.io/"
languageCode = "en-us"
title = "HydroSense Lab, IIT Delhi"
themesDir = "./themes"
theme = "hugo-serif-theme"
relativeURLs = true
publishDir = "docs"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "UA-92542844-3"
  google_tag_manager_id = ""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo2.svg"
    alt = "HydroSense Lab, IIT Delhi"

  [params.homepage_meta_tags]
    meta_description = "The HydroSense Lab of IIT Delhi develops solutions for effective management of water resources and reducing the impact of natural hazards. Led by Dr. Manabendra Saharia."
    meta_og_title = "HydroSense Lab, IIT Delhi"
    meta_og_type = "website"
    meta_og_url = "https://hydrosenselab.github.io"
    meta_og_description = "The HydroSense Lab of IIT Delhi develops solutions for effective management of water resources and reducing the impact of natural hazards. Led by Dr. Manabendra Saharia."
    meta_twitter_card = "summary"
    meta_twitter_site = "@m_saharia"
    meta_twitter_creator = "@m_saharia"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Research"
    url = "/research/"
      weight = 2

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
      weight = 4

  [[menu.main]]
      name = "Teaching"
      url = "/teaching/"
      weight = 6

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 8

  [[menu.main]]
      name = "News and Achievements"
      url = "/achievements/"
      weight = 10

  [[menu.main]]
      name = "Join"
      url = "/join/"
      weight = 12

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 14

  # Footer Menu
